<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CS0618;CS8600;CS8601;CS8602;CS8605;CS8618;CS8622;CS8625;CS8632</NoWarn>
    <Platforms>x64;arm64</Platforms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Configurations>Debug;Release;Debug Portable;Release Portable;Release Installer;Deploy to github</Configurations>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Console" />
    <PackageReference Include="NUnit.ConsoleRunner" />
    <PackageReference Include="NUnit.Extension.TeamCityEventListener" />
    <PackageReference Include="NUnit.Runners" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\mRemoteNG.PluginContracts\mRemoteNG.PluginContracts.csproj" />
    <ProjectReference Include="..\mRemoteNG.Plugins.MultiAddress\mRemoteNG.Plugins.MultiAddress.csproj" />
  </ItemGroup>
</Project>
