
// 
// This code was generated by a script. Any changes made manually will be lost
// the next time this code is regenerated.
//

using System.Reflection;
using System.Resources;

// General Information
[assembly: AssemblyTitle("mRemoteNG")]
[assembly: AssemblyDescription("Multi-Remote Next Generation Connection Manager")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("mRemoteNG")]
[assembly: AssemblyProduct("mRemoteNG Connection Manager")]
[assembly: AssemblyCopyright("(c) 2024 mRemoteNG")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Version information
[assembly: AssemblyVersion("1.77.3.1827")]
[assembly: AssemblyFileVersion("1.77.3.1827")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersion("1.77.3 (Nightly Build 1827)")]

// Logging
[assembly: log4net.Config.XmlConfigurator(ConfigFile = "log4net.config")]

