//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mRemoteNG.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class OptionsGoogleDrivePage : global::System.Configuration.ApplicationSettingsBase {

        private static OptionsGoogleDrivePage defaultInstance = ((OptionsGoogleDrivePage)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OptionsGoogleDrivePage())));

        public static OptionsGoogleDrivePage Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseGoogleDrive {
            get {
                return ((bool)(this["UseGoogleDrive"]));
            }
            set {
                this["UseGoogleDrive"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mRemoteNG_connections.xml")]
        public string GoogleDriveFileName {
            get {
                return ((string)(this["GoogleDriveFileName"]));
            }
            set {
                this["GoogleDriveFileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleDriveFileId {
            get {
                return ((string)(this["GoogleDriveFileId"]));
            }
            set {
                this["GoogleDriveFileId"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleDriveCredentialsPath {
            get {
                return ((string)(this["GoogleDriveCredentialsPath"]));
            }
            set {
                this["GoogleDriveCredentialsPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbGoogleDrivePageInOptionMenu {
            get {
                return ((bool)(this["cbGoogleDrivePageInOptionMenu"]));
            }
            set {
                this["cbGoogleDrivePageInOptionMenu"] = value;
            }
        }
    }
}
