//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mRemoteNG.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class OptionsUpdatesPage : global::System.Configuration.ApplicationSettingsBase {
        
        private static OptionsUpdatesPage defaultInstance = ((OptionsUpdatesPage)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OptionsUpdatesPage())));
        
        public static OptionsUpdatesPage Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdatePending {
            get {
                return ((bool)(this["UpdatePending"]));
            }
            set {
                this["UpdatePending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("release")]
        public string UpdateChannel {
            get {
                return ((string)(this["UpdateChannel"]));
            }
            set {
                this["UpdateChannel"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mremoteng.org/")]
        public string UpdateAddress {
            get {
                return ((string)(this["UpdateAddress"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateProxyAddress {
            get {
                return ((string)(this["UpdateProxyAddress"]));
            }
            set {
                this["UpdateProxyAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateProxyAuthPass {
            get {
                return ((string)(this["UpdateProxyAuthPass"]));
            }
            set {
                this["UpdateProxyAuthPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateProxyAuthUser {
            get {
                return ((string)(this["UpdateProxyAuthUser"]));
            }
            set {
                this["UpdateProxyAuthUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int UpdateProxyPort {
            get {
                return ((int)(this["UpdateProxyPort"]));
            }
            set {
                this["UpdateProxyPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdateProxyUseAuthentication {
            get {
                return ((bool)(this["UpdateProxyUseAuthentication"]));
            }
            set {
                this["UpdateProxyUseAuthentication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdateUseProxy {
            get {
                return ((bool)(this["UpdateUseProxy"]));
            }
            set {
                this["UpdateUseProxy"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dev")]
        public string CurrentUpdateChannelType {
            get {
                return ((string)(this["CurrentUpdateChannelType"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdatesOnStartup {
            get {
                return ((bool)(this["CheckForUpdatesOnStartup"]));
            }
            set {
                this["CheckForUpdatesOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1980-01-01")]
        public global::System.DateTime CheckForUpdatesLastCheck {
            get {
                return ((global::System.DateTime)(this["CheckForUpdatesLastCheck"]));
            }
            set {
                this["CheckForUpdatesLastCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int CheckForUpdatesFrequencyDays {
            get {
                return ((int)(this["CheckForUpdatesFrequencyDays"]));
            }
            set {
                this["CheckForUpdatesFrequencyDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckForUpdatesAsked {
            get {
                return ((bool)(this["CheckForUpdatesAsked"]));
            }
            set {
                this["CheckForUpdatesAsked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cbUpdatesPageInOptionMenu {
            get {
                return ((bool)(this["cbUpdatesPageInOptionMenu"]));
            }
            set {
                this["cbUpdatesPageInOptionMenu"] = value;
            }
        }
    }
}
