//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mRemoteNG.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleClickOnConnectionOpensIt {
            get {
                return ((bool)(this["SingleClickOnConnectionOpensIt"]));
            }
            set {
                this["SingleClickOnConnectionOpensIt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultDescription {
            get {
                return ((string)(this["ConDefaultDescription"]));
            }
            set {
                this["ConDefaultDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RDP")]
        public string ConDefaultProtocol {
            get {
                return ((string)(this["ConDefaultProtocol"]));
            }
            set {
                this["ConDefaultProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eu-central-1")]
        public string ConDefaultEC2Region {
            get {
                return ((string)(this["ConDefaultEC2Region"]));
            }
            set {
                this["ConDefaultEC2Region"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default Settings")]
        public string ConDefaultPuttySession {
            get {
                return ((string)(this["ConDefaultPuttySession"]));
            }
            set {
                this["ConDefaultPuttySession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultUseConsoleSession {
            get {
                return ((bool)(this["ConDefaultUseConsoleSession"]));
            }
            set {
                this["ConDefaultUseConsoleSession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FitToWindow")]
        public string ConDefaultResolution {
            get {
                return ((string)(this["ConDefaultResolution"]));
            }
            set {
                this["ConDefaultResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Colors16Bit")]
        public string ConDefaultColors {
            get {
                return ((string)(this["ConDefaultColors"]));
            }
            set {
                this["ConDefaultColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultCacheBitmaps {
            get {
                return ((bool)(this["ConDefaultCacheBitmaps"]));
            }
            set {
                this["ConDefaultCacheBitmaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultDisplayWallpaper {
            get {
                return ((bool)(this["ConDefaultDisplayWallpaper"]));
            }
            set {
                this["ConDefaultDisplayWallpaper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultDisplayThemes {
            get {
                return ((bool)(this["ConDefaultDisplayThemes"]));
            }
            set {
                this["ConDefaultDisplayThemes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectKeys {
            get {
                return ((bool)(this["ConDefaultRedirectKeys"]));
            }
            set {
                this["ConDefaultRedirectKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Local")]
        public string ConDefaultRedirectDiskDrives {
            get {
                return ((string)(this["ConDefaultRedirectDiskDrives"]));
            }
            set {
                this["ConDefaultRedirectDiskDrives"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRedirectDiskDrivesCustom
        {
            get
            {
                return ((string)(this["ConDefaultRedirectDiskDrivesCustom"]));
            }
            set
            {
                this["ConDefaultRedirectDiskDrivesCustom"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectPrinters {
            get {
                return ((bool)(this["ConDefaultRedirectPrinters"]));
            }
            set {
                this["ConDefaultRedirectPrinters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectClipboard {
            get {
                return ((bool)(this["ConDefaultRedirectClipboard"]));
            }
            set {
                this["ConDefaultRedirectClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectPorts {
            get {
                return ((bool)(this["ConDefaultRedirectPorts"]));
            }
            set {
                this["ConDefaultRedirectPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectSmartCards {
            get {
                return ((bool)(this["ConDefaultRedirectSmartCards"]));
            }
            set {
                this["ConDefaultRedirectSmartCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DoNotPlay")]
        public string ConDefaultRedirectSound {
            get {
                return ((string)(this["ConDefaultRedirectSound"]));
            }
            set {
                this["ConDefaultRedirectSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectAudioCapture {
            get {
                return ((bool)(this["ConDefaultRedirectAudioCapture"]));
            }
            set {
                this["ConDefaultRedirectAudioCapture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtAppsTBVisible {
            get {
                return ((bool)(this["ExtAppsTBVisible"]));
            }
            set {
                this["ExtAppsTBVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExtAppsTBShowText {
            get {
                return ((bool)(this["ExtAppsTBShowText"]));
            }
            set {
                this["ExtAppsTBShowText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ExtAppsTBLocation {
            get {
                return ((global::System.Drawing.Point)(this["ExtAppsTBLocation"]));
            }
            set {
                this["ExtAppsTBLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bottom")]
        public string ExtAppsTBParentDock {
            get {
                return ((string)(this["ExtAppsTBParentDock"]));
            }
            set {
                this["ExtAppsTBParentDock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickyTBVisible {
            get {
                return ((bool)(this["QuickyTBVisible"]));
            }
            set {
                this["QuickyTBVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 24")]
        public global::System.Drawing.Point QuickyTBLocation {
            get {
                return ((global::System.Drawing.Point)(this["QuickyTBLocation"]));
            }
            set {
                this["QuickyTBLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top")]
        public string QuickyTBParentDock {
            get {
                return ((string)(this["QuickyTBParentDock"]));
            }
            set {
                this["QuickyTBParentDock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultCacheBitmaps {
            get {
                return ((bool)(this["InhDefaultCacheBitmaps"]));
            }
            set {
                this["InhDefaultCacheBitmaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultColors {
            get {
                return ((bool)(this["InhDefaultColors"]));
            }
            set {
                this["InhDefaultColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDescription {
            get {
                return ((bool)(this["InhDefaultDescription"]));
            }
            set {
                this["InhDefaultDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDisplayThemes {
            get {
                return ((bool)(this["InhDefaultDisplayThemes"]));
            }
            set {
                this["InhDefaultDisplayThemes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDisplayWallpaper {
            get {
                return ((bool)(this["InhDefaultDisplayWallpaper"]));
            }
            set {
                this["InhDefaultDisplayWallpaper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDomain {
            get {
                return ((bool)(this["InhDefaultDomain"]));
            }
            set {
                this["InhDefaultDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultIcon {
            get {
                return ((bool)(this["InhDefaultIcon"]));
            }
            set {
                this["InhDefaultIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultPassword {
            get {
                return ((bool)(this["InhDefaultPassword"]));
            }
            set {
                this["InhDefaultPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultPort {
            get {
                return ((bool)(this["InhDefaultPort"]));
            }
            set {
                this["InhDefaultPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultProtocol {
            get {
                return ((bool)(this["InhDefaultProtocol"]));
            }
            set {
                this["InhDefaultProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultPuttySession {
            get {
                return ((bool)(this["InhDefaultPuttySession"]));
            }
            set {
                this["InhDefaultPuttySession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectDiskDrives {
            get {
                return ((bool)(this["InhDefaultRedirectDiskDrives"]));
            }
            set {
                this["InhDefaultRedirectDiskDrives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectKeys {
            get {
                return ((bool)(this["InhDefaultRedirectKeys"]));
            }
            set {
                this["InhDefaultRedirectKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectPorts {
            get {
                return ((bool)(this["InhDefaultRedirectPorts"]));
            }
            set {
                this["InhDefaultRedirectPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectPrinters {
            get {
                return ((bool)(this["InhDefaultRedirectPrinters"]));
            }
            set {
                this["InhDefaultRedirectPrinters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectClipboard {
            get {
                return ((bool)(this["InhDefaultRedirectClipboard"]));
            }
            set {
                this["InhDefaultRedirectClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectSmartCards {
            get {
                return ((bool)(this["InhDefaultRedirectSmartCards"]));
            }
            set {
                this["InhDefaultRedirectSmartCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectSound {
            get {
                return ((bool)(this["InhDefaultRedirectSound"]));
            }
            set {
                this["InhDefaultRedirectSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectAudioCapture {
            get {
                return ((bool)(this["InhDefaultRedirectAudioCapture"]));
            }
            set {
                this["InhDefaultRedirectAudioCapture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultResolution {
            get {
                return ((bool)(this["InhDefaultResolution"]));
            }
            set {
                this["InhDefaultResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUseConsoleSession {
            get {
                return ((bool)(this["InhDefaultUseConsoleSession"]));
            }
            set {
                this["InhDefaultUseConsoleSession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUsername {
            get {
                return ((bool)(this["InhDefaultUsername"]));
            }
            set {
                this["InhDefaultUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultPanel {
            get {
                return ((bool)(this["InhDefaultPanel"]));
            }
            set {
                this["InhDefaultPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultPreExtApp {
            get {
                return ((string)(this["ConDefaultPreExtApp"]));
            }
            set {
                this["ConDefaultPreExtApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultPostExtApp {
            get {
                return ((string)(this["ConDefaultPostExtApp"]));
            }
            set {
                this["ConDefaultPostExtApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultPreExtApp {
            get {
                return ((bool)(this["InhDefaultPreExtApp"]));
            }
            set {
                this["InhDefaultPreExtApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultPostExtApp {
            get {
                return ((bool)(this["InhDefaultPostExtApp"]));
            }
            set {
                this["InhDefaultPostExtApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetHostnameLikeDisplayName {
            get {
                return ((bool)(this["SetHostnameLikeDisplayName"]));
            }
            set {
                this["SetHostnameLikeDisplayName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AuthVNC")]
        public string ConDefaultVNCAuthMode {
            get {
                return ((string)(this["ConDefaultVNCAuthMode"]));
            }
            set {
                this["ConDefaultVNCAuthMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ColNormal")]
        public string ConDefaultVNCColors {
            get {
                return ((string)(this["ConDefaultVNCColors"]));
            }
            set {
                this["ConDefaultVNCColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SmartSAspect")]
        public string ConDefaultVNCSmartSizeMode {
            get {
                return ((string)(this["ConDefaultVNCSmartSizeMode"]));
            }
            set {
                this["ConDefaultVNCSmartSizeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultVNCViewOnly {
            get {
                return ((bool)(this["ConDefaultVNCViewOnly"]));
            }
            set {
                this["ConDefaultVNCViewOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CompNone")]
        public string ConDefaultVNCCompression {
            get {
                return ((string)(this["ConDefaultVNCCompression"]));
            }
            set {
                this["ConDefaultVNCCompression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EncHextile")]
        public string ConDefaultVNCEncoding {
            get {
                return ((string)(this["ConDefaultVNCEncoding"]));
            }
            set {
                this["ConDefaultVNCEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultVNCProxyIP {
            get {
                return ((string)(this["ConDefaultVNCProxyIP"]));
            }
            set {
                this["ConDefaultVNCProxyIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultVNCProxyPassword {
            get {
                return ((string)(this["ConDefaultVNCProxyPassword"]));
            }
            set {
                this["ConDefaultVNCProxyPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConDefaultVNCProxyPort {
            get {
                return ((int)(this["ConDefaultVNCProxyPort"]));
            }
            set {
                this["ConDefaultVNCProxyPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProxyNone")]
        public string ConDefaultVNCProxyType {
            get {
                return ((string)(this["ConDefaultVNCProxyType"]));
            }
            set {
                this["ConDefaultVNCProxyType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultVNCProxyUsername {
            get {
                return ((string)(this["ConDefaultVNCProxyUsername"]));
            }
            set {
                this["ConDefaultVNCProxyUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCAuthMode {
            get {
                return ((bool)(this["InhDefaultVNCAuthMode"]));
            }
            set {
                this["InhDefaultVNCAuthMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCColors {
            get {
                return ((bool)(this["InhDefaultVNCColors"]));
            }
            set {
                this["InhDefaultVNCColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCSmartSizeMode {
            get {
                return ((bool)(this["InhDefaultVNCSmartSizeMode"]));
            }
            set {
                this["InhDefaultVNCSmartSizeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCViewOnly {
            get {
                return ((bool)(this["InhDefaultVNCViewOnly"]));
            }
            set {
                this["InhDefaultVNCViewOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCCompression {
            get {
                return ((bool)(this["InhDefaultVNCCompression"]));
            }
            set {
                this["InhDefaultVNCCompression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCEncoding {
            get {
                return ((bool)(this["InhDefaultVNCEncoding"]));
            }
            set {
                this["InhDefaultVNCEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCProxyIP {
            get {
                return ((bool)(this["InhDefaultVNCProxyIP"]));
            }
            set {
                this["InhDefaultVNCProxyIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCProxyPassword {
            get {
                return ((bool)(this["InhDefaultVNCProxyPassword"]));
            }
            set {
                this["InhDefaultVNCProxyPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCProxyPort {
            get {
                return ((bool)(this["InhDefaultVNCProxyPort"]));
            }
            set {
                this["InhDefaultVNCProxyPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCProxyType {
            get {
                return ((bool)(this["InhDefaultVNCProxyType"]));
            }
            set {
                this["InhDefaultVNCProxyType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVNCProxyUsername {
            get {
                return ((bool)(this["InhDefaultVNCProxyUsername"]));
            }
            set {
                this["InhDefaultVNCProxyUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleClickSwitchesToOpenConnection {
            get {
                return ((bool)(this["SingleClickSwitchesToOpenConnection"]));
            }
            set {
                this["SingleClickSwitchesToOpenConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoAuth")]
        public string ConDefaultRDPAuthenticationLevel {
            get {
                return ((string)(this["ConDefaultRDPAuthenticationLevel"]));
            }
            set {
                this["ConDefaultRDPAuthenticationLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDPAuthenticationLevel {
            get {
                return ((bool)(this["InhDefaultRDPAuthenticationLevel"]));
            }
            set {
                this["InhDefaultRDPAuthenticationLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XULRunnerPath {
            get {
                return ((string)(this["XULRunnerPath"]));
            }
            set {
                this["XULRunnerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRenderingEngine {
            get {
                return ((bool)(this["InhDefaultRenderingEngine"]));
            }
            set {
                this["InhDefaultRenderingEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultMacAddress {
            get {
                return ((string)(this["ConDefaultMacAddress"]));
            }
            set {
                this["ConDefaultMacAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultMacAddress {
            get {
                return ((bool)(this["InhDefaultMacAddress"]));
            }
            set {
                this["InhDefaultMacAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultUserField {
            get {
                return ((string)(this["ConDefaultUserField"]));
            }
            set {
                this["ConDefaultUserField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUserField {
            get {
                return ((bool)(this["InhDefaultUserField"]));
            }
            set {
                this["InhDefaultUserField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultExtApp {
            get {
                return ((string)(this["ConDefaultExtApp"]));
            }
            set {
                this["ConDefaultExtApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultExtApp {
            get {
                return ((bool)(this["InhDefaultExtApp"]));
            }
            set {
                this["InhDefaultExtApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Never")]
        public string ConDefaultRDGatewayUsageMethod {
            get {
                return ((string)(this["ConDefaultRDGatewayUsageMethod"]));
            }
            set {
                this["ConDefaultRDGatewayUsageMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yes")]
        public string ConDefaultRDGatewayUseConnectionCredentials {
            get {
                return ((string)(this["ConDefaultRDGatewayUseConnectionCredentials"]));
            }
            set {
                this["ConDefaultRDGatewayUseConnectionCredentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mRemoteNG")]
        public string ConDefaultIcon {
            get {
                return ((string)(this["ConDefaultIcon"]));
            }
            set {
                this["ConDefaultIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayUsageMethod {
            get {
                return ((bool)(this["InhDefaultRDGatewayUsageMethod"]));
            }
            set {
                this["InhDefaultRDGatewayUsageMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayHostname {
            get {
                return ((bool)(this["InhDefaultRDGatewayHostname"]));
            }
            set {
                this["InhDefaultRDGatewayHostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayUsername {
            get {
                return ((bool)(this["InhDefaultRDGatewayUsername"]));
            }
            set {
                this["InhDefaultRDGatewayUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayPassword {
            get {
                return ((bool)(this["InhDefaultRDGatewayPassword"]));
            }
            set {
                this["InhDefaultRDGatewayPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayDomain {
            get {
                return ((bool)(this["InhDefaultRDGatewayDomain"]));
            }
            set {
                this["InhDefaultRDGatewayDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayUseConnectionCredentials {
            get {
                return ((bool)(this["InhDefaultRDGatewayUseConnectionCredentials"]));
            }
            set {
                this["InhDefaultRDGatewayUseConnectionCredentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RdpReconnectionCount {
            get {
                return ((int)(this["RdpReconnectionCount"]));
            }
            set {
                this["RdpReconnectionCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OverrideUICulture {
            get {
                return ((string)(this["OverrideUICulture"]));
            }
            set {
                this["OverrideUICulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDGatewayHostname {
            get {
                return ((string)(this["ConDefaultRDGatewayHostname"]));
            }
            set {
                this["ConDefaultRDGatewayHostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDGatewayUsername {
            get {
                return ((string)(this["ConDefaultRDGatewayUsername"]));
            }
            set {
                this["ConDefaultRDGatewayUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDGatewayPassword {
            get {
                return ((string)(this["ConDefaultRDGatewayPassword"]));
            }
            set {
                this["ConDefaultRDGatewayPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDGatewayDomain {
            get {
                return ((string)(this["ConDefaultRDGatewayDomain"]));
            }
            set {
                this["ConDefaultRDGatewayDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultEnableFontSmoothing {
            get {
                return ((bool)(this["ConDefaultEnableFontSmoothing"]));
            }
            set {
                this["ConDefaultEnableFontSmoothing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultEnableFontSmoothing {
            get {
                return ((bool)(this["InhDefaultEnableFontSmoothing"]));
            }
            set {
                this["InhDefaultEnableFontSmoothing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultEnableDesktopComposition {
            get {
                return ((bool)(this["ConDefaultEnableDesktopComposition"]));
            }
            set {
                this["ConDefaultEnableDesktopComposition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultEnableDesktopComposition {
            get {
                return ((bool)(this["InhDefaultEnableDesktopComposition"]));
            }
            set {
                this["InhDefaultEnableDesktopComposition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDisableFullWindowDrag {
            get {
                return ((bool)(this["InhDefaultDisableFullWindowDrag"]));
            }
            set {
                this["InhDefaultDisableFullWindowDrag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDisableMenuAnimations {
            get {
                return ((bool)(this["InhDefaultDisableMenuAnimations"]));
            }
            set {
                this["InhDefaultDisableMenuAnimations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDisableCursorShadow {
            get {
                return ((bool)(this["InhDefaultDisableCursorShadow"]));
            }
            set {
                this["InhDefaultDisableCursorShadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDisableCursorBlinking {
            get {
                return ((bool)(this["InhDefaultDisableCursorBlinking"]));
            }
            set {
                this["InhDefaultDisableCursorBlinking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ConfirmCloseConnection {
            get {
                return ((int)(this["ConfirmCloseConnection"]));
            }
            set {
                this["ConfirmCloseConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUseCredSsp {
            get {
                return ((bool)(this["InhDefaultUseCredSsp"]));
            }
            set {
                this["InhDefaultUseCredSsp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConDefaultUseCredSsp {
            get {
                return ((bool)(this["ConDefaultUseCredSsp"]));
            }
            set {
                this["ConDefaultUseCredSsp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUseRestrictedAdmin {
            get {
                return ((bool)(this["InhDefaultUseRestrictedAdmin"]));
            }
            set {
                this["InhDefaultUseRestrictedAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultUseRestrictedAdmin {
            get {
                return ((bool)(this["ConDefaultUseRestrictedAdmin"]));
            }
            set {
                this["ConDefaultUseRestrictedAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUseRCG {
            get {
                return ((bool)(this["InhDefaultUseRCG"]));
            }
            set {
                this["InhDefaultUseRCG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultUseRCG {
            get {
                return ((bool)(this["ConDefaultUseRCG"]));
            }
            set {
                this["ConDefaultUseRCG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultUseVmId {
            get {
                return ((bool)(this["ConDefaultUseVmId"]));
            }
            set {
                this["ConDefaultUseVmId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowConfigHelpText {
            get {
                return ((bool)(this["ShowConfigHelpText"]));
            }
            set {
                this["ShowConfigHelpText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PuttySavedSessionsName {
            get {
                return ((string)(this["PuttySavedSessionsName"]));
            }
            set {
                this["PuttySavedSessionsName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PuttySavedSessionsPanel {
            get {
                return ((string)(this["PuttySavedSessionsPanel"]));
            }
            set {
                this["PuttySavedSessionsPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CompatibilityWarnLenovoAutoScrollUtility {
            get {
                return ((bool)(this["CompatibilityWarnLenovoAutoScrollUtility"]));
            }
            set {
                this["CompatibilityWarnLenovoAutoScrollUtility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultLoadBalanceInfo {
            get {
                return ((string)(this["ConDefaultLoadBalanceInfo"]));
            }
            set {
                this["ConDefaultLoadBalanceInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConDefaultAutomaticResize {
            get {
                return ((bool)(this["ConDefaultAutomaticResize"]));
            }
            set {
                this["ConDefaultAutomaticResize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultLoadBalanceInfo {
            get {
                return ((bool)(this["InhDefaultLoadBalanceInfo"]));
            }
            set {
                this["InhDefaultLoadBalanceInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultAutomaticResize {
            get {
                return ((bool)(this["InhDefaultAutomaticResize"]));
            }
            set {
                this["InhDefaultAutomaticResize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RDP")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string QuickConnectProtocol {
            get {
                return ((string)(this["QuickConnectProtocol"]));
            }
            set {
                this["QuickConnectProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9/9, 33/8")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string KeysPreviousTab {
            get {
                return ((string)(this["KeysPreviousTab"]));
            }
            set {
                this["KeysPreviousTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9/8, 34/8")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string KeysNextTab {
            get {
                return ((string)(this["KeysNextTab"]));
            }
            set {
                this["KeysNextTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ConRDPOverallConnectionTimeout {
            get {
                return ((int)(this["ConRDPOverallConnectionTimeout"]));
            }
            set {
                this["ConRDPOverallConnectionTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dynamic")]
        public string ConDefaultSoundQuality {
            get {
                return ((string)(this["ConDefaultSoundQuality"]));
            }
            set {
                this["ConDefaultSoundQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultSoundQuality {
            get {
                return ((bool)(this["InhDefaultSoundQuality"]));
            }
            set {
                this["InhDefaultSoundQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConDefaultRDPMinutesToIdleTimeout {
            get {
                return ((int)(this["ConDefaultRDPMinutesToIdleTimeout"]));
            }
            set {
                this["ConDefaultRDPMinutesToIdleTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDPMinutesToIdleTimeout {
            get {
                return ((bool)(this["InhDefaultRDPMinutesToIdleTimeout"]));
            }
            set {
                this["InhDefaultRDPMinutesToIdleTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRDPAlertIdleTimeout {
            get {
                return ((bool)(this["ConDefaultRDPAlertIdleTimeout"]));
            }
            set {
                this["ConDefaultRDPAlertIdleTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDPAlertIdleTimeout {
            get {
                return ((bool)(this["InhDefaultRDPAlertIdleTimeout"]));
            }
            set {
                this["InhDefaultRDPAlertIdleTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultCredentialRecord {
            get {
                return ((bool)(this["InhDefaultCredentialRecord"]));
            }
            set {
                this["InhDefaultCredentialRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid ConDefaultCredentialRecord {
            get {
                return ((global::System.Guid)(this["ConDefaultCredentialRecord"]));
            }
            set {
                this["ConDefaultCredentialRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PromptUnlockCredReposOnStartup {
            get {
                return ((bool)(this["PromptUnlockCredReposOnStartup"]));
            }
            set {
                this["PromptUnlockCredReposOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultUsername {
            get {
                return ((string)(this["ConDefaultUsername"]));
            }
            set {
                this["ConDefaultUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultPassword {
            get {
                return ((string)(this["ConDefaultPassword"]));
            }
            set {
                this["ConDefaultPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultDomain {
            get {
                return ((string)(this["ConDefaultDomain"]));
            }
            set {
                this["ConDefaultDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("General")]
        public string ConDefaultPanel {
            get {
                return ((string)(this["ConDefaultPanel"]));
            }
            set {
                this["ConDefaultPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseFilterSearch {
            get {
                return ((bool)(this["UseFilterSearch"]));
            }
            set {
                this["UseFilterSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockToolbars {
            get {
                return ((bool)(this["LockToolbars"]));
            }
            set {
                this["LockToolbars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MultiSshToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["MultiSshToolbarLocation"]));
            }
            set {
                this["MultiSshToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MultiSshToolbarParentDock {
            get {
                return ((string)(this["MultiSshToolbarParentDock"]));
            }
            set {
                this["MultiSshToolbarParentDock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MultiSshToolbarVisible {
            get {
                return ((bool)(this["MultiSshToolbarVisible"]));
            }
            set {
                this["MultiSshToolbarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrackActiveConnectionInConnectionTree {
            get {
                return ((bool)(this["TrackActiveConnectionInConnectionTree"]));
            }
            set {
                this["TrackActiveConnectionInConnectionTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlaceSearchBarAboveConnectionTree {
            get {
                return ((bool)(this["PlaceSearchBarAboveConnectionTree"]));
            }
            set {
                this["PlaceSearchBarAboveConnectionTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverrideFIPSCheck {
            get {
                return ((bool)(this["OverrideFIPSCheck"]));
            }
            set {
                this["OverrideFIPSCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultFavorite {
            get {
                return ((bool)(this["ConDefaultFavorite"]));
            }
            set {
                this["ConDefaultFavorite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultFavorite {
            get {
                return ((bool)(this["InhDefaultFavorite"]));
            }
            set {
                this["InhDefaultFavorite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoNotTrimUsername {
            get {
                return ((bool)(this["DoNotTrimUsername"]));
            }
            set {
                this["DoNotTrimUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultVmId {
            get {
                return ((string)(this["ConDefaultVmId"]));
            }
            set {
                this["ConDefaultVmId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultVmId {
            get {
                return ((bool)(this["InhDefaultVmId"]));
            }
            set {
                this["InhDefaultVmId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUseVmId {
            get {
                return ((bool)(this["InhDefaultUseVmId"]));
            }
            set {
                this["InhDefaultUseVmId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Highest")]
        public string ConDefaultRdpVersion {
            get {
                return ((string)(this["ConDefaultRdpVersion"]));
            }
            set {
                this["ConDefaultRdpVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRdpVersion {
            get {
                return ((bool)(this["InhDefaultRdpVersion"]));
            }
            set {
                this["InhDefaultRdpVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultSSHTunnelConnectionName {
            get {
                return ((bool)(this["InhDefaultSSHTunnelConnectionName"]));
            }
            set {
                this["InhDefaultSSHTunnelConnectionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultSSHTunnelConnectionName {
            get {
                return ((string)(this["ConDefaultSSHTunnelConnectionName"]));
            }
            set {
                this["ConDefaultSSHTunnelConnectionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultSSHOptions {
            get {
                return ((bool)(this["InhDefaultSSHOptions"]));
            }
            set {
                this["InhDefaultSSHOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultSSHOptions {
            get {
                return ((string)(this["ConDefaultSSHOptions"]));
            }
            set {
                this["ConDefaultSSHOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultUseEnhancedMode {
            get {
                return ((bool)(this["ConDefaultUseEnhancedMode"]));
            }
            set {
                this["ConDefaultUseEnhancedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUseEnhancedMode {
            get {
                return ((bool)(this["InhDefaultUseEnhancedMode"]));
            }
            set {
                this["InhDefaultUseEnhancedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartupComponentsCheck {
            get {
                return ((bool)(this["StartupComponentsCheck"]));
            }
            set {
                this["StartupComponentsCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultDisableFullWindowDrag {
            get {
                return ((bool)(this["ConDefaultDisableFullWindowDrag"]));
            }
            set {
                this["ConDefaultDisableFullWindowDrag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultDisableMenuAnimations {
            get {
                return ((bool)(this["ConDefaultDisableMenuAnimations"]));
            }
            set {
                this["ConDefaultDisableMenuAnimations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultDisableCursorShadow {
            get {
                return ((bool)(this["ConDefaultDisableCursorShadow"]));
            }
            set {
                this["ConDefaultDisableCursorShadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultDisableCursorBlinking {
            get {
                return ((bool)(this["ConDefaultDisableCursorBlinking"]));
            }
            set {
                this["ConDefaultDisableCursorBlinking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultStartProgram {
            get {
                return ((string)(this["ConDefaultStartProgram"]));
            }
            set {
                this["ConDefaultStartProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultStartProgramWorkDir {
            get {
                return ((string)(this["ConDefaultStartProgramWorkDir"]));
            }
            set {
                this["ConDefaultStartProgramWorkDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EncrBasic")]
        public string ConDefaultICAEncryptionStrength {
            get {
                return ((string)(this["ConDefaultICAEncryptionStrength"]));
            }
            set {
                this["ConDefaultICAEncryptionStrength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string InhDefaultICAEncryptionStrength {
            get {
                return ((string)(this["InhDefaultICAEncryptionStrength"]));
            }
            set {
                this["InhDefaultICAEncryptionStrength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewMenuMessages {
            get {
                return ((bool)(this["ViewMenuMessages"]));
            }
            set {
                this["ViewMenuMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewMenuQuickConnect {
            get {
                return ((bool)(this["ViewMenuQuickConnect"]));
            }
            set {
                this["ViewMenuQuickConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewMenuExternalTools {
            get {
                return ((bool)(this["ViewMenuExternalTools"]));
            }
            set {
                this["ViewMenuExternalTools"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewMenuMultiSSH {
            get {
                return ((bool)(this["ViewMenuMultiSSH"]));
            }
            set {
                this["ViewMenuMultiSSH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EdgeChromium")]
        public string ConDefaultRenderingEngine {
            get {
                return ((string)(this["ConDefaultRenderingEngine"]));
            }
            set {
                this["ConDefaultRenderingEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpeningCommand {
            get {
                return ((string)(this["OpeningCommand"]));
            }
            set {
                this["OpeningCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDPStartProgram {
            get {
                return ((string)(this["ConDefaultRDPStartProgram"]));
            }
            set {
                this["ConDefaultRDPStartProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDPStartProgramWorkDir {
            get {
                return ((string)(this["ConDefaultRDPStartProgramWorkDir"]));
            }
            set {
                this["ConDefaultRDPStartProgramWorkDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultEC2InstanceId {
            get {
                return ((string)(this["ConDefaultEC2InstanceId"]));
            }
            set {
                this["ConDefaultEC2InstanceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultUserViaAPI {
            get {
                return ((string)(this["ConDefaultUserViaAPI"]));
            }
            set {
                this["ConDefaultUserViaAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultOpeningCommand {
            get {
                return ((string)(this["ConDefaultOpeningCommand"]));
            }
            set {
                this["ConDefaultOpeningCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUserViaAPI {
            get {
                return ((bool)(this["InhDefaultUserViaAPI"]));
            }
            set {
                this["InhDefaultUserViaAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultOpeningCommand {
            get {
                return ((bool)(this["InhDefaultOpeningCommand"]));
            }
            set {
                this["InhDefaultOpeningCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ConDefaultExternalCredentialProvider {
            get {
                return ((string)(this["ConDefaultExternalCredentialProvider"]));
            }
            set {
                this["ConDefaultExternalCredentialProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultExternalCredentialProvider {
            get {
                return ((bool)(this["InhDefaultExternalCredentialProvider"]));
            }
            set {
                this["InhDefaultExternalCredentialProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ConDefaultExternalAddressProvider {
            get {
                return ((string)(this["ConDefaultExternalAddressProvider"]));
            }
            set {
                this["ConDefaultExternalAddressProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultExternalAddressProvider {
            get {
                return ((bool)(this["InhDefaultExternalAddressProvider"]));
            }
            set {
                this["InhDefaultExternalAddressProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDGatewayUserViaAPI {
            get {
                return ((string)(this["ConDefaultRDGatewayUserViaAPI"]));
            }
            set {
                this["ConDefaultRDGatewayUserViaAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ConDefaultRDGatewayExternalCredentialProvider {
            get {
                return ((string)(this["ConDefaultRDGatewayExternalCredentialProvider"]));
            }
            set {
                this["ConDefaultRDGatewayExternalCredentialProvider"] = value;
            }
        }
    }
}
