// VBConversions Note: VB project level imports
using System.Collections.Generic;
using System;
using AxWFICALib;
using System.Drawing;
using System.Diagnostics;
using System.Data;
using AxMSTSCLib;
using Microsoft.VisualBasic;
using System.Collections;
using System.Windows.Forms;
// End of VB project level imports

using System.Threading;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace mRemoteNG
{
	namespace My
	{
		
		[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"), 
		global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
		{
			
			private static Settings defaultInstance = (My.Settings) (global::System.Configuration.ApplicationSettingsBase.Synchronized(new My.Settings()));
			
#region My.Settings Auto-Save Functionality
#if _MyType
			private static bool addedHandler;
			
			private static object addedHandlerLockObject = new object();
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]private static void AutoSaveSettings(global::System.Object sender, global::System.EventArgs e)
			{
				if ((new Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase()).SaveMySettingsOnExit)
				{
					My.Settings.Default.Save();
				}
			}
#endif
#endregion
			
public static Settings Default
			{
				get
				{
					
#if _MyType
					if (!addedHandler)
					{
						lock(addedHandlerLockObject)
						{
							if (!addedHandler)
							{
								(new Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase).Shutdown += AutoSaveSettings;
								addedHandler = true;
							}
						}
					}
#endif
					return defaultInstance;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute()]public global::System.Drawing.Point MainFormLocation
			{
				get
				{
					return ((global::System.Drawing.Point) (this["MainFormLocation"]));
				}
				set
				{
					this["MainFormLocation"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute()]public global::System.Drawing.Size MainFormSize
			{
				get
				{
					return ((global::System.Drawing.Size) (this["MainFormSize"]));
				}
				set
				{
					this["MainFormSize"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("Normal")]public global::System.Windows.Forms.FormWindowState MainFormState
			{
				get
				{
					return ((global::System.Windows.Forms.FormWindowState) (this["MainFormState"]));
				}
				set
				{
					this["MainFormState"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool MainFormKiosk
			{
				get
				{
					return System.Convert.ToBoolean(this["MainFormKiosk"]);
				}
				set
				{
					this["MainFormKiosk"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool DoUpgrade
			{
				get
				{
					return System.Convert.ToBoolean(this["DoUpgrade"]);
				}
				set
				{
					this["DoUpgrade"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string CustomPuttyPath
			{
				get
				{
					return System.Convert.ToString(this["CustomPuttyPath"]);
				}
				set
				{
					this["CustomPuttyPath"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool ShowNoMessageBoxes
			{
				get
				{
					return System.Convert.ToBoolean(this["ShowNoMessageBoxes"]);
				}
				set
				{
					this["ShowNoMessageBoxes"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool SwitchToMCOnInformation
			{
				get
				{
					return System.Convert.ToBoolean(this["SwitchToMCOnInformation"]);
				}
				set
				{
					this["SwitchToMCOnInformation"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool SwitchToMCOnWarning
			{
				get
				{
					return System.Convert.ToBoolean(this["SwitchToMCOnWarning"]);
				}
				set
				{
					this["SwitchToMCOnWarning"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool SwitchToMCOnError
			{
				get
				{
					return System.Convert.ToBoolean(this["SwitchToMCOnError"]);
				}
				set
				{
					this["SwitchToMCOnError"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool AutomaticallyGetSessionInfo
			{
				get
				{
					return System.Convert.ToBoolean(this["AutomaticallyGetSessionInfo"]);
				}
				set
				{
					this["AutomaticallyGetSessionInfo"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool LoadConsFromCustomLocation
			{
				get
				{
					return System.Convert.ToBoolean(this["LoadConsFromCustomLocation"]);
				}
				set
				{
					this["LoadConsFromCustomLocation"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string CustomConsPath
			{
				get
				{
					return System.Convert.ToString(this["CustomConsPath"]);
				}
				set
				{
					this["CustomConsPath"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool SaveConsOnExit
			{
				get
				{
					return System.Convert.ToBoolean(this["SaveConsOnExit"]);
				}
				set
				{
					this["SaveConsOnExit"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool CheckForUpdatesOnStartup
			{
				get
				{
					return System.Convert.ToBoolean(this["CheckForUpdatesOnStartup"]);
				}
				set
				{
					this["CheckForUpdatesOnStartup"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ShowDescriptionTooltipsInTree
			{
				get
				{
					return System.Convert.ToBoolean(this["ShowDescriptionTooltipsInTree"]);
				}
				set
				{
					this["ShowDescriptionTooltipsInTree"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ShowSystemTrayIcon
			{
				get
				{
					return System.Convert.ToBoolean(this["ShowSystemTrayIcon"]);
				}
				set
				{
					this["ShowSystemTrayIcon"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool OpenTabsRightOfSelected
			{
				get
				{
					return System.Convert.ToBoolean(this["OpenTabsRightOfSelected"]);
				}
				set
				{
					this["OpenTabsRightOfSelected"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ShowLogonInfoOnTabs
			{
				get
				{
					return System.Convert.ToBoolean(this["ShowLogonInfoOnTabs"]);
				}
				set
				{
					this["ShowLogonInfoOnTabs"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool SingleClickOnConnectionOpensIt
			{
				get
				{
					return System.Convert.ToBoolean(this["SingleClickOnConnectionOpensIt"]);
				}
				set
				{
					this["SingleClickOnConnectionOpensIt"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("noinfo")]public string EmptyCredentials
			{
				get
				{
					return System.Convert.ToString(this["EmptyCredentials"]);
				}
				set
				{
					this["EmptyCredentials"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string DefaultUsername
			{
				get
				{
					return System.Convert.ToString(this["DefaultUsername"]);
				}
				set
				{
					this["DefaultUsername"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string DefaultPassword
			{
				get
				{
					return System.Convert.ToString(this["DefaultPassword"]);
				}
				set
				{
					this["DefaultPassword"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string DefaultDomain
			{
				get
				{
					return System.Convert.ToString(this["DefaultDomain"]);
				}
				set
				{
					this["DefaultDomain"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool WriteLogFile
			{
				get
				{
					return System.Convert.ToBoolean(this["WriteLogFile"]);
				}
				set
				{
					this["WriteLogFile"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool UseCustomPuttyPath
			{
				get
				{
					return System.Convert.ToBoolean(this["UseCustomPuttyPath"]);
				}
				set
				{
					this["UseCustomPuttyPath"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ShowCompleteConsPathInTitle
			{
				get
				{
					return System.Convert.ToBoolean(this["ShowCompleteConsPathInTitle"]);
				}
				set
				{
					this["ShowCompleteConsPathInTitle"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool FirstStart
			{
				get
				{
					return System.Convert.ToBoolean(this["FirstStart"]);
				}
				set
				{
					this["FirstStart"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ShowProtocolOnTabs
			{
				get
				{
					return System.Convert.ToBoolean(this["ShowProtocolOnTabs"]);
				}
				set
				{
					this["ShowProtocolOnTabs"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ResetPanels
			{
				get
				{
					return System.Convert.ToBoolean(this["ResetPanels"]);
				}
				set
				{
					this["ResetPanels"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool UpdateUseProxy
			{
				get
				{
					return System.Convert.ToBoolean(this["UpdateUseProxy"]);
				}
				set
				{
					this["UpdateUseProxy"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string UpdateProxyAddress
			{
				get
				{
					return System.Convert.ToString(this["UpdateProxyAddress"]);
				}
				set
				{
					this["UpdateProxyAddress"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("80")]public int UpdateProxyPort
			{
				get
				{
					return System.Convert.ToInt32(this["UpdateProxyPort"]);
				}
				set
				{
					this["UpdateProxyPort"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool UpdateProxyUseAuthentication
			{
				get
				{
					return System.Convert.ToBoolean(this["UpdateProxyUseAuthentication"]);
				}
				set
				{
					this["UpdateProxyUseAuthentication"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string UpdateProxyAuthUser
			{
				get
				{
					return System.Convert.ToString(this["UpdateProxyAuthUser"]);
				}
				set
				{
					this["UpdateProxyAuthUser"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string UpdateProxyAuthPass
			{
				get
				{
					return System.Convert.ToString(this["UpdateProxyAuthPass"]);
				}
				set
				{
					this["UpdateProxyAuthPass"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultDescription
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultDescription"]);
				}
				set
				{
					this["ConDefaultDescription"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultUsername
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultUsername"]);
				}
				set
				{
					this["ConDefaultUsername"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultPassword
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultPassword"]);
				}
				set
				{
					this["ConDefaultPassword"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultDomain
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultDomain"]);
				}
				set
				{
					this["ConDefaultDomain"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("RDP")]public string ConDefaultProtocol
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultProtocol"]);
				}
				set
				{
					this["ConDefaultProtocol"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("Default Settings")]public string ConDefaultPuttySession
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultPuttySession"]);
				}
				set
				{
					this["ConDefaultPuttySession"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultUseConsoleSession
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultUseConsoleSession"]);
				}
				set
				{
					this["ConDefaultUseConsoleSession"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("FitToWindow")]public string ConDefaultResolution
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultResolution"]);
				}
				set
				{
					this["ConDefaultResolution"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("Colors16Bit")]public string ConDefaultColors
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultColors"]);
				}
				set
				{
					this["ConDefaultColors"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool ConDefaultCacheBitmaps
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultCacheBitmaps"]);
				}
				set
				{
					this["ConDefaultCacheBitmaps"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultDisplayWallpaper
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultDisplayWallpaper"]);
				}
				set
				{
					this["ConDefaultDisplayWallpaper"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultDisplayThemes
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultDisplayThemes"]);
				}
				set
				{
					this["ConDefaultDisplayThemes"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultRedirectKeys
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultRedirectKeys"]);
				}
				set
				{
					this["ConDefaultRedirectKeys"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultRedirectDiskDrives
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultRedirectDiskDrives"]);
				}
				set
				{
					this["ConDefaultRedirectDiskDrives"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultRedirectPrinters
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultRedirectPrinters"]);
				}
				set
				{
					this["ConDefaultRedirectPrinters"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultRedirectPorts
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultRedirectPorts"]);
				}
				set
				{
					this["ConDefaultRedirectPorts"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultRedirectSmartCards
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultRedirectSmartCards"]);
				}
				set
				{
					this["ConDefaultRedirectSmartCards"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("DoNotPlay")]public string ConDefaultRedirectSound
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultRedirectSound"]);
				}
				set
				{
					this["ConDefaultRedirectSound"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("2")]public int MaxPuttyWaitTime
			{
				get
				{
					return System.Convert.ToInt32(this["MaxPuttyWaitTime"]);
				}
				set
				{
					this["MaxPuttyWaitTime"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool SingleInstance
			{
				get
				{
					return System.Convert.ToBoolean(this["SingleInstance"]);
				}
				set
				{
					this["SingleInstance"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool OpenConsFromLastSession
			{
				get
				{
					return System.Convert.ToBoolean(this["OpenConsFromLastSession"]);
				}
				set
				{
					this["OpenConsFromLastSession"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool NoReconnect
			{
				get
				{
					return System.Convert.ToBoolean(this["NoReconnect"]);
				}
				set
				{
					this["NoReconnect"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("0")]public int AutoSaveEveryMinutes
			{
				get
				{
					return System.Convert.ToInt32(this["AutoSaveEveryMinutes"]);
				}
				set
				{
					this["AutoSaveEveryMinutes"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ExtAppsTBVisible
			{
				get
				{
					return System.Convert.ToBoolean(this["ExtAppsTBVisible"]);
				}
				set
				{
					this["ExtAppsTBVisible"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool ExtAppsTBShowText
			{
				get
				{
					return System.Convert.ToBoolean(this["ExtAppsTBShowText"]);
				}
				set
				{
					this["ExtAppsTBShowText"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("0, 0")]public global::System.Drawing.Point ExtAppsTBLocation
			{
				get
				{
					return ((global::System.Drawing.Point) (this["ExtAppsTBLocation"]));
				}
				set
				{
					this["ExtAppsTBLocation"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("Bottom")]public string ExtAppsTBParentDock
			{
				get
				{
					return System.Convert.ToString(this["ExtAppsTBParentDock"]);
				}
				set
				{
					this["ExtAppsTBParentDock"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool QuickyTBVisible
			{
				get
				{
					return System.Convert.ToBoolean(this["QuickyTBVisible"]);
				}
				set
				{
					this["QuickyTBVisible"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("3, 24")]public global::System.Drawing.Point QuickyTBLocation
			{
				get
				{
					return ((global::System.Drawing.Point) (this["QuickyTBLocation"]));
				}
				set
				{
					this["QuickyTBLocation"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("Top")]public string QuickyTBParentDock
			{
				get
				{
					return System.Convert.ToString(this["QuickyTBParentDock"]);
				}
				set
				{
					this["QuickyTBParentDock"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ResetToolbars
			{
				get
				{
					return System.Convert.ToBoolean(this["ResetToolbars"]);
				}
				set
				{
					this["ResetToolbars"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool UseSQLServer
			{
				get
				{
					return System.Convert.ToBoolean(this["UseSQLServer"]);
				}
				set
				{
					this["UseSQLServer"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string SQLHost
			{
				get
				{
					return System.Convert.ToString(this["SQLHost"]);
				}
				set
				{
					this["SQLHost"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string SQLUser
			{
				get
				{
					return System.Convert.ToString(this["SQLUser"]);
				}
				set
				{
					this["SQLUser"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string SQLPass
			{
				get
				{
					return System.Convert.ToString(this["SQLPass"]);
				}
				set
				{
					this["SQLPass"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultCacheBitmaps
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultCacheBitmaps"]);
				}
				set
				{
					this["InhDefaultCacheBitmaps"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultColors
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultColors"]);
				}
				set
				{
					this["InhDefaultColors"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultDescription
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultDescription"]);
				}
				set
				{
					this["InhDefaultDescription"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultDisplayThemes
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultDisplayThemes"]);
				}
				set
				{
					this["InhDefaultDisplayThemes"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultDisplayWallpaper
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultDisplayWallpaper"]);
				}
				set
				{
					this["InhDefaultDisplayWallpaper"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultDomain
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultDomain"]);
				}
				set
				{
					this["InhDefaultDomain"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultIcon
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultIcon"]);
				}
				set
				{
					this["InhDefaultIcon"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultPassword
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultPassword"]);
				}
				set
				{
					this["InhDefaultPassword"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultPort
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultPort"]);
				}
				set
				{
					this["InhDefaultPort"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultProtocol
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultProtocol"]);
				}
				set
				{
					this["InhDefaultProtocol"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultPuttySession
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultPuttySession"]);
				}
				set
				{
					this["InhDefaultPuttySession"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRedirectDiskDrives
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRedirectDiskDrives"]);
				}
				set
				{
					this["InhDefaultRedirectDiskDrives"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRedirectKeys
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRedirectKeys"]);
				}
				set
				{
					this["InhDefaultRedirectKeys"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRedirectPorts
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRedirectPorts"]);
				}
				set
				{
					this["InhDefaultRedirectPorts"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRedirectPrinters
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRedirectPrinters"]);
				}
				set
				{
					this["InhDefaultRedirectPrinters"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRedirectSmartCards
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRedirectSmartCards"]);
				}
				set
				{
					this["InhDefaultRedirectSmartCards"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRedirectSound
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRedirectSound"]);
				}
				set
				{
					this["InhDefaultRedirectSound"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultResolution
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultResolution"]);
				}
				set
				{
					this["InhDefaultResolution"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultUseConsoleSession
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultUseConsoleSession"]);
				}
				set
				{
					this["InhDefaultUseConsoleSession"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultUsername
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultUsername"]);
				}
				set
				{
					this["InhDefaultUsername"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultPanel
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultPanel"]);
				}
				set
				{
					this["InhDefaultPanel"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("EncrBasic")]public string ConDefaultICAEncryptionStrength
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultICAEncryptionStrength"]);
				}
				set
				{
					this["ConDefaultICAEncryptionStrength"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultICAEncryptionStrength
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultICAEncryptionStrength"]);
				}
				set
				{
					this["InhDefaultICAEncryptionStrength"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultPreExtApp
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultPreExtApp"]);
				}
				set
				{
					this["ConDefaultPreExtApp"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultPostExtApp
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultPostExtApp"]);
				}
				set
				{
					this["ConDefaultPostExtApp"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultPreExtApp
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultPreExtApp"]);
				}
				set
				{
					this["InhDefaultPreExtApp"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultPostExtApp
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultPostExtApp"]);
				}
				set
				{
					this["InhDefaultPostExtApp"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool SetHostnameLikeDisplayName
			{
				get
				{
					return System.Convert.ToBoolean(this["SetHostnameLikeDisplayName"]);
				}
				set
				{
					this["SetHostnameLikeDisplayName"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool DoubleClickOnTabClosesIt
			{
				get
				{
					return System.Convert.ToBoolean(this["DoubleClickOnTabClosesIt"]);
				}
				set
				{
					this["DoubleClickOnTabClosesIt"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ReconnectOnDisconnect
			{
				get
				{
					return System.Convert.ToBoolean(this["ReconnectOnDisconnect"]);
				}
				set
				{
					this["ReconnectOnDisconnect"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool AlwaysShowPanelSelectionDlg
			{
				get
				{
					return System.Convert.ToBoolean(this["AlwaysShowPanelSelectionDlg"]);
				}
				set
				{
					this["AlwaysShowPanelSelectionDlg"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("AuthVNC")]public string ConDefaultVNCAuthMode
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultVNCAuthMode"]);
				}
				set
				{
					this["ConDefaultVNCAuthMode"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("ColNormal")]public string ConDefaultVNCColors
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultVNCColors"]);
				}
				set
				{
					this["ConDefaultVNCColors"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("SmartSAspect")]public string ConDefaultVNCSmartSizeMode
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultVNCSmartSizeMode"]);
				}
				set
				{
					this["ConDefaultVNCSmartSizeMode"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultVNCViewOnly
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultVNCViewOnly"]);
				}
				set
				{
					this["ConDefaultVNCViewOnly"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("CompNone")]public string ConDefaultVNCCompression
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultVNCCompression"]);
				}
				set
				{
					this["ConDefaultVNCCompression"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("EncHextile")]public string ConDefaultVNCEncoding
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultVNCEncoding"]);
				}
				set
				{
					this["ConDefaultVNCEncoding"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultVNCProxyIP
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultVNCProxyIP"]);
				}
				set
				{
					this["ConDefaultVNCProxyIP"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultVNCProxyPassword
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultVNCProxyPassword"]);
				}
				set
				{
					this["ConDefaultVNCProxyPassword"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("0")]public int ConDefaultVNCProxyPort
			{
				get
				{
					return System.Convert.ToInt32(this["ConDefaultVNCProxyPort"]);
				}
				set
				{
					this["ConDefaultVNCProxyPort"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("ProxyNone")]public string ConDefaultVNCProxyType
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultVNCProxyType"]);
				}
				set
				{
					this["ConDefaultVNCProxyType"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultVNCProxyUsername
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultVNCProxyUsername"]);
				}
				set
				{
					this["ConDefaultVNCProxyUsername"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCAuthMode
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCAuthMode"]);
				}
				set
				{
					this["InhDefaultVNCAuthMode"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCColors
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCColors"]);
				}
				set
				{
					this["InhDefaultVNCColors"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCSmartSizeMode
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCSmartSizeMode"]);
				}
				set
				{
					this["InhDefaultVNCSmartSizeMode"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCViewOnly
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCViewOnly"]);
				}
				set
				{
					this["InhDefaultVNCViewOnly"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCCompression
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCCompression"]);
				}
				set
				{
					this["InhDefaultVNCCompression"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCEncoding
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCEncoding"]);
				}
				set
				{
					this["InhDefaultVNCEncoding"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCProxyIP
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCProxyIP"]);
				}
				set
				{
					this["InhDefaultVNCProxyIP"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCProxyPassword
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCProxyPassword"]);
				}
				set
				{
					this["InhDefaultVNCProxyPassword"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCProxyPort
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCProxyPort"]);
				}
				set
				{
					this["InhDefaultVNCProxyPort"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCProxyType
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCProxyType"]);
				}
				set
				{
					this["InhDefaultVNCProxyType"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultVNCProxyUsername
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultVNCProxyUsername"]);
				}
				set
				{
					this["InhDefaultVNCProxyUsername"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool MinimizeToTray
			{
				get
				{
					return System.Convert.ToBoolean(this["MinimizeToTray"]);
				}
				set
				{
					this["MinimizeToTray"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool SingleClickSwitchesToOpenConnection
			{
				get
				{
					return System.Convert.ToBoolean(this["SingleClickSwitchesToOpenConnection"]);
				}
				set
				{
					this["SingleClickSwitchesToOpenConnection"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("NoAuth")]public string ConDefaultRDPAuthenticationLevel
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultRDPAuthenticationLevel"]);
				}
				set
				{
					this["ConDefaultRDPAuthenticationLevel"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRDPAuthenticationLevel
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRDPAuthenticationLevel"]);
				}
				set
				{
					this["InhDefaultRDPAuthenticationLevel"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("5500")]public int UVNCSCPort
			{
				get
				{
					return System.Convert.ToInt32(this["UVNCSCPort"]);
				}
				set
				{
					this["UVNCSCPort"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool StartupComponentsCheck
			{
				get
				{
					return System.Convert.ToBoolean(this["StartupComponentsCheck"]);
				}
				set
				{
					this["StartupComponentsCheck"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string XULRunnerPath
			{
				get
				{
					return System.Convert.ToString(this["XULRunnerPath"]);
				}
				set
				{
					this["XULRunnerPath"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("IE")]public string ConDefaultRenderingEngine
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultRenderingEngine"]);
				}
				set
				{
					this["ConDefaultRenderingEngine"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRenderingEngine
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRenderingEngine"]);
				}
				set
				{
					this["InhDefaultRenderingEngine"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultMacAddress
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultMacAddress"]);
				}
				set
				{
					this["ConDefaultMacAddress"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultMacAddress
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultMacAddress"]);
				}
				set
				{
					this["InhDefaultMacAddress"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool EncryptCompleteConnectionsFile
			{
				get
				{
					return System.Convert.ToBoolean(this["EncryptCompleteConnectionsFile"]);
				}
				set
				{
					this["EncryptCompleteConnectionsFile"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultUserField
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultUserField"]);
				}
				set
				{
					this["ConDefaultUserField"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultUserField
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultUserField"]);
				}
				set
				{
					this["InhDefaultUserField"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultExtApp
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultExtApp"]);
				}
				set
				{
					this["ConDefaultExtApp"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultExtApp
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultExtApp"]);
				}
				set
				{
					this["InhDefaultExtApp"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string LastAnnouncement
			{
				get
				{
					return System.Convert.ToString(this["LastAnnouncement"]);
				}
				set
				{
					this["LastAnnouncement"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool CheckForUpdatesAsked
			{
				get
				{
					return System.Convert.ToBoolean(this["CheckForUpdatesAsked"]);
				}
				set
				{
					this["CheckForUpdatesAsked"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("7")]public int CheckForUpdatesFrequencyDays
			{
				get
				{
					return System.Convert.ToInt32(this["CheckForUpdatesFrequencyDays"]);
				}
				set
				{
					this["CheckForUpdatesFrequencyDays"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("1980-01-01")]public DateTime CheckForUpdatesLastCheck
			{
				get
				{
					return System.Convert.ToDateTime(this["CheckForUpdatesLastCheck"]);
				}
				set
				{
					this["CheckForUpdatesLastCheck"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool UpdatePending
			{
				get
				{
					return System.Convert.ToBoolean(this["UpdatePending"]);
				}
				set
				{
					this["UpdatePending"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("Never")]public string ConDefaultRDGatewayUsageMethod
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultRDGatewayUsageMethod"]);
				}
				set
				{
					this["ConDefaultRDGatewayUsageMethod"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("Yes")]public string ConDefaultRDGatewayUseConnectionCredentials
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultRDGatewayUseConnectionCredentials"]);
				}
				set
				{
					this["ConDefaultRDGatewayUseConnectionCredentials"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("mRemoteNG")]public string ConDefaultIcon
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultIcon"]);
				}
				set
				{
					this["ConDefaultIcon"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRDGatewayUsageMethod
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRDGatewayUsageMethod"]);
				}
				set
				{
					this["InhDefaultRDGatewayUsageMethod"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRDGatewayHostname
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRDGatewayHostname"]);
				}
				set
				{
					this["InhDefaultRDGatewayHostname"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRDGatewayUsername
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRDGatewayUsername"]);
				}
				set
				{
					this["InhDefaultRDGatewayUsername"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRDGatewayPassword
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRDGatewayPassword"]);
				}
				set
				{
					this["InhDefaultRDGatewayPassword"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRDGatewayDomain
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRDGatewayDomain"]);
				}
				set
				{
					this["InhDefaultRDGatewayDomain"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultRDGatewayUseConnectionCredentials
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultRDGatewayUseConnectionCredentials"]);
				}
				set
				{
					this["InhDefaultRDGatewayUseConnectionCredentials"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("5")]public int RdpReconnectionCount
			{
				get
				{
					return System.Convert.ToInt32(this["RdpReconnectionCount"]);
				}
				set
				{
					this["RdpReconnectionCount"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string OverrideUICulture
			{
				get
				{
					return System.Convert.ToString(this["OverrideUICulture"]);
				}
				set
				{
					this["OverrideUICulture"] = value;
				}
			}
			
[global::System.Configuration.ApplicationScopedSettingAttribute(), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("de,el,en,en-US,es-AR,es,fr,hu,it,nb-NO,nl,pt,pt-BR,pl,ru,uk,zh-CN,zh-TW")]public string SupportedUICultures
			{
				get
				{
					return System.Convert.ToString(this["SupportedUICultures"]);
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultRDGatewayHostname
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultRDGatewayHostname"]);
				}
				set
				{
					this["ConDefaultRDGatewayHostname"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultRDGatewayUsername
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultRDGatewayUsername"]);
				}
				set
				{
					this["ConDefaultRDGatewayUsername"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultRDGatewayPassword
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultRDGatewayPassword"]);
				}
				set
				{
					this["ConDefaultRDGatewayPassword"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultRDGatewayDomain
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultRDGatewayDomain"]);
				}
				set
				{
					this["ConDefaultRDGatewayDomain"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultEnableFontSmoothing
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultEnableFontSmoothing"]);
				}
				set
				{
					this["ConDefaultEnableFontSmoothing"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultEnableFontSmoothing
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultEnableFontSmoothing"]);
				}
				set
				{
					this["InhDefaultEnableFontSmoothing"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool ConDefaultEnableDesktopComposition
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultEnableDesktopComposition"]);
				}
				set
				{
					this["ConDefaultEnableDesktopComposition"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultEnableDesktopComposition
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultEnableDesktopComposition"]);
				}
				set
				{
					this["InhDefaultEnableDesktopComposition"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("4")]public int ConfirmCloseConnection
			{
				get
				{
					return System.Convert.ToInt32(this["ConfirmCloseConnection"]);
				}
				set
				{
					this["ConfirmCloseConnection"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute()]public global::System.Drawing.Size MainFormRestoreSize
			{
				get
				{
					return ((global::System.Drawing.Size) (this["MainFormRestoreSize"]));
				}
				set
				{
					this["MainFormRestoreSize"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute()]public global::System.Drawing.Point MainFormRestoreLocation
			{
				get
				{
					return ((global::System.Drawing.Point) (this["MainFormRestoreLocation"]));
				}
				set
				{
					this["MainFormRestoreLocation"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("mRemoteNG")]public string SQLDatabaseName
			{
				get
				{
					return System.Convert.ToString(this["SQLDatabaseName"]);
				}
				set
				{
					this["SQLDatabaseName"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("10"), 
global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]public int BackupFileKeepCount
			{
				get
				{
					return System.Convert.ToInt32(this["BackupFileKeepCount"]);
				}
				set
				{
					this["BackupFileKeepCount"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("{0}.{1:yyyyMMdd-HHmmssffff}.backup"), 
global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]public string BackupFileNameFormat
			{
				get
				{
					return System.Convert.ToString(this["BackupFileNameFormat"]);
				}
				set
				{
					this["BackupFileNameFormat"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultUseCredSsp
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultUseCredSsp"]);
				}
				set
				{
					this["InhDefaultUseCredSsp"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool ConDefaultUseCredSsp
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultUseCredSsp"]);
				}
				set
				{
					this["ConDefaultUseCredSsp"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False"), 
global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]public bool AlwaysShowPanelTabs
			{
				get
				{
					return System.Convert.ToBoolean(this["AlwaysShowPanelTabs"]);
				}
				set
				{
					this["AlwaysShowPanelTabs"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False"), 
global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]public bool IdentifyQuickConnectTabs
			{
				get
				{
					return System.Convert.ToBoolean(this["IdentifyQuickConnectTabs"]);
				}
				set
				{
					this["IdentifyQuickConnectTabs"] = value;
				}
			}
			
[global::System.Configuration.ApplicationScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("release")]public string UpdateChannel
			{
				get
				{
					return System.Convert.ToString(this["UpdateChannel"]);
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ThemeName
			{
				get
				{
					return System.Convert.ToString(this["ThemeName"]);
				}
				set
				{
					this["ThemeName"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool ShowConfigHelpText
			{
				get
				{
					return System.Convert.ToBoolean(this["ShowConfigHelpText"]);
				}
				set
				{
					this["ShowConfigHelpText"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string PuttySavedSessionsName
			{
				get
				{
					return System.Convert.ToString(this["PuttySavedSessionsName"]);
				}
				set
				{
					this["PuttySavedSessionsName"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string PuttySavedSessionsPanel
			{
				get
				{
					return System.Convert.ToString(this["PuttySavedSessionsPanel"]);
				}
				set
				{
					this["PuttySavedSessionsPanel"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool CompatibilityWarnLenovoAutoScrollUtility
			{
				get
				{
					return System.Convert.ToBoolean(this["CompatibilityWarnLenovoAutoScrollUtility"]);
				}
				set
				{
					this["CompatibilityWarnLenovoAutoScrollUtility"] = value;
				}
			}
			
[global::System.Configuration.ApplicationScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("https://update.mremoteng.org/announcement.txt")]public string AnnouncementAddress
			{
				get
				{
					return System.Convert.ToString(this["AnnouncementAddress"]);
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("https://update.mremoteng.org/")]public string UpdateAddress
			{
				get
				{
					return System.Convert.ToString(this["UpdateAddress"]);
				}
				set
				{
					this["UpdateAddress"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string ConDefaultLoadBalanceInfo
			{
				get
				{
					return System.Convert.ToString(this["ConDefaultLoadBalanceInfo"]);
				}
				set
				{
					this["ConDefaultLoadBalanceInfo"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("True")]public bool ConDefaultAutomaticResize
			{
				get
				{
					return System.Convert.ToBoolean(this["ConDefaultAutomaticResize"]);
				}
				set
				{
					this["ConDefaultAutomaticResize"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultLoadBalanceInfo
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultLoadBalanceInfo"]);
				}
				set
				{
					this["InhDefaultLoadBalanceInfo"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public bool InhDefaultAutomaticResize
			{
				get
				{
					return System.Convert.ToBoolean(this["InhDefaultAutomaticResize"]);
				}
				set
				{
					this["InhDefaultAutomaticResize"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("RDP"), 
global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]public string QuickConnectProtocol
			{
				get
				{
					return System.Convert.ToString(this["QuickConnectProtocol"]);
				}
				set
				{
					this["QuickConnectProtocol"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("9/9, 33/8"), 
global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]public string KeysPreviousTab
			{
				get
				{
					return System.Convert.ToString(this["KeysPreviousTab"]);
				}
				set
				{
					this["KeysPreviousTab"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
global::System.Configuration.SettingsProviderAttribute(typeof(mRemoteNG.Config.Settings.Providers.ChooseProvider)), 
global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
global::System.Configuration.DefaultSettingValueAttribute("9/8, 34/8"), 
global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]public string KeysNextTab
			{
				get
				{
					return System.Convert.ToString(this["KeysNextTab"]);
				}
				set
				{
					this["KeysNextTab"] = value;
				}
			}
		}
	}
	
	namespace My
	{
		
		[global::Microsoft.VisualBasic.HideModuleNameAttribute(), 
		global::System.Diagnostics.DebuggerNonUserCodeAttribute(), 
		global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]internal sealed class MySettingsProperty
		{
			
[global::System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")]internal static global::mRemoteNG.My.Settings Settings
			{
				get
				{
					return global::mRemoteNG.My.Settings.Default;
				}
			}
		}
	}
	
}
