//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mRemoteNG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColorMapTheme {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorMapTheme() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mRemoteNG.Resources.Themes.ColorMapTheme", typeof(ColorMapTheme).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;Button&apos;]/Background/@Source.
        /// </summary>
        internal static string Button_Background {
            get {
                return ResourceManager.GetString("Button_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonBorder&apos;]/Background/@Source.
        /// </summary>
        internal static string Button_Border {
            get {
                return ResourceManager.GetString("Button_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonDisabled&apos;]/Background/@Source.
        /// </summary>
        internal static string Button_Disabled_Background {
            get {
                return ResourceManager.GetString("Button_Disabled_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonBorderDisabled&apos;]/Background/@Source.
        /// </summary>
        internal static string Button_Disabled_Border {
            get {
                return ResourceManager.GetString("Button_Disabled_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonDisabled&apos;]/Foreground/@Source.
        /// </summary>
        internal static string Button_Disabled_Foreground {
            get {
                return ResourceManager.GetString("Button_Disabled_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;Button&apos;]/Foreground/@Source.
        /// </summary>
        internal static string Button_Foreground {
            get {
                return ResourceManager.GetString("Button_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonHover&apos;]/Background/@Source.
        /// </summary>
        internal static string Button_Hover_Background {
            get {
                return ResourceManager.GetString("Button_Hover_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonBorderHover&apos;]/Background/@Source.
        /// </summary>
        internal static string Button_Hover_Border {
            get {
                return ResourceManager.GetString("Button_Hover_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonHover&apos;]/Foreground/@Source.
        /// </summary>
        internal static string Button_Hover_Foreground {
            get {
                return ResourceManager.GetString("Button_Hover_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonPressed&apos;]/Background/@Source.
        /// </summary>
        internal static string Button_Pressed_Background {
            get {
                return ResourceManager.GetString("Button_Pressed_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonBorderPressed&apos;]/Background/@Source.
        /// </summary>
        internal static string Button_Pressed_Border {
            get {
                return ResourceManager.GetString("Button_Pressed_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;ButtonPressed&apos;]/Foreground/@Source.
        /// </summary>
        internal static string Button_Pressed_Foreground {
            get {
                return ResourceManager.GetString("Button_Pressed_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Text Editor Text Marker Items&apos;]/Color[@Name=&apos;compiler error&apos;]/Background/@Source.
        /// </summary>
        internal static string ErrorText_Background {
            get {
                return ResourceManager.GetString("ErrorText_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Text Editor Text Marker Items&apos;]/Color[@Name=&apos;compiler error&apos;]/Foreground/@Source.
        /// </summary>
        internal static string ErrorText_Foreground {
            get {
                return ResourceManager.GetString("ErrorText_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListBackground&apos;]/Background/@Source.
        /// </summary>
        internal static string List_Background {
            get {
                return ResourceManager.GetString("List_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListHeader&apos;]/Background/@Source.
        /// </summary>
        internal static string List_Header_Background {
            get {
                return ResourceManager.GetString("List_Header_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListHeader&apos;]/Foreground/@Source.
        /// </summary>
        internal static string List_Header_Foreground {
            get {
                return ResourceManager.GetString("List_Header_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItem&apos;]/Background/@Source.
        /// </summary>
        internal static string List_Item_Background {
            get {
                return ResourceManager.GetString("List_Item_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemBorder&apos;]/Background/@Source.
        /// </summary>
        internal static string List_Item_Border {
            get {
                return ResourceManager.GetString("List_Item_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemDisabled&apos;]/Background/@Source.
        /// </summary>
        internal static string List_Item_Disabled_Background {
            get {
                return ResourceManager.GetString("List_Item_Disabled_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemDisabledBorder&apos;]/Background/@Source.
        /// </summary>
        internal static string List_Item_Disabled_Border {
            get {
                return ResourceManager.GetString("List_Item_Disabled_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemDisabled&apos;]/Foreground/@Source.
        /// </summary>
        internal static string List_Item_Disabled_Foreground {
            get {
                return ResourceManager.GetString("List_Item_Disabled_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItem&apos;]/Foreground/@Source.
        /// </summary>
        internal static string List_Item_Foreground {
            get {
                return ResourceManager.GetString("List_Item_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemSelected&apos;]/Background/@Source.
        /// </summary>
        internal static string List_Item_Selected_Background {
            get {
                return ResourceManager.GetString("List_Item_Selected_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemSelectedBorder&apos;]/Background/@Source.
        /// </summary>
        internal static string List_Item_Selected_Border {
            get {
                return ResourceManager.GetString("List_Item_Selected_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Cider&apos;]/Color[@Name=&apos;ListItemSelected&apos;]/Foreground/@Source.
        /// </summary>
        internal static string List_Item_Selected_Foreground {
            get {
                return ResourceManager.GetString("List_Item_Selected_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBackground&apos;]/Background/@Source.
        /// </summary>
        internal static string TextBox_Background {
            get {
                return ResourceManager.GetString("TextBox_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBorder&apos;]/Background/@Source.
        /// </summary>
        internal static string TextBox_Border {
            get {
                return ResourceManager.GetString("TextBox_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBorderDisabled&apos;]/Background/@Source.
        /// </summary>
        internal static string TextBox_Border_Disabled {
            get {
                return ResourceManager.GetString("TextBox_Border_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBorderFocused&apos;]/Background/@Source.
        /// </summary>
        internal static string TextBox_Border_Focused {
            get {
                return ResourceManager.GetString("TextBox_Border_Focused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBackgroundDisabled&apos;]/Background/@Source.
        /// </summary>
        internal static string TextBox_Disabled_Background {
            get {
                return ResourceManager.GetString("TextBox_Disabled_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxTextDisabled&apos;]/Background/@Source.
        /// </summary>
        internal static string TextBox_Disabled_Foreground {
            get {
                return ResourceManager.GetString("TextBox_Disabled_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxBackgroundFocused&apos;]/Background/@Source.
        /// </summary>
        internal static string TextBox_Focused_Background {
            get {
                return ResourceManager.GetString("TextBox_Focused_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxTextFocused&apos;]/Background/@Source.
        /// </summary>
        internal static string TextBox_Focused_Foreground {
            get {
                return ResourceManager.GetString("TextBox_Focused_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;CommonControls&apos;]/Color[@Name=&apos;TextBoxText&apos;]/Background/@Source.
        /// </summary>
        internal static string TextBox_Foreground {
            get {
                return ResourceManager.GetString("TextBox_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;Background&apos;]/Background/@Source.
        /// </summary>
        internal static string TreeView_Background {
            get {
                return ResourceManager.GetString("TreeView_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;Background&apos;]/Foreground/@Source.
        /// </summary>
        internal static string TreeView_Foreground {
            get {
                return ResourceManager.GetString("TreeView_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;SelectedItemActive&apos;]/Background/@Source.
        /// </summary>
        internal static string Treeview_SelectedItem_Active_Background {
            get {
                return ResourceManager.GetString("Treeview_SelectedItem_Active_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;SelectedItemActive&apos;]/Foreground/@Source.
        /// </summary>
        internal static string Treeview_SelectedItem_Active_Foreground {
            get {
                return ResourceManager.GetString("Treeview_SelectedItem_Active_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;SelectedItemInactive&apos;]/Background/@Source.
        /// </summary>
        internal static string Treeview_SelectedItem_Inactive_Background {
            get {
                return ResourceManager.GetString("Treeview_SelectedItem_Inactive_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;TreeView&apos;]/Color[@Name=&apos;SelectedItemInactive&apos;]/Foreground/@Source.
        /// </summary>
        internal static string Treeview_SelectedItem_Inactive_Foreground {
            get {
                return ResourceManager.GetString("Treeview_SelectedItem_Inactive_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Text Editor Text Marker Items&apos;]/Color[@Name=&apos;compiler warning&apos;]/Background/@Source.
        /// </summary>
        internal static string WarningText_Background {
            get {
                return ResourceManager.GetString("WarningText_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Themes/Theme/Category[@Name=&apos;Text Editor Text Marker Items&apos;]/Color[@Name=&apos;compiler warning&apos;]/Foreground/@Source.
        /// </summary>
        internal static string WarningText_Foreground {
            get {
                return ResourceManager.GetString("WarningText_Foreground", resourceCulture);
            }
        }
    }
}
